server:
  port: 8080
  servlet:
    context-path: /

spring:
  application: 
    name: GraphQL

  datasource:
    url: jdbc:postgresql://walmartassignment.postgres.database.azure.com:5432/walmartassignment
    username: admin1214
    password: Allen1214$
  jpa:
    database-platform: postgres
    show-sql: true
    hibernate:
      ddl-auto: create
